spring:
  scheduler:
    # cycle scheduler(1000 -> 1sec)
    cycle:
      live-check:
        delay: 30000
    
    # cron-batch scheduler
    cron:
      file-read-db-write-batch:
        use-yn: Y
        cron-cycle: "0 04 12 * * *"
        chunk-size: 1000
        read-file-path: "C://workspace_platform/spring-batch-mybatis-jpa/files/read.txt"
      db-read-file-write-batch:
        use-yn: N
        cron-cycle: "0 47 09 * * *"
        chunk-size: 1000
        write-file-path: "C://workspace_platform/spring-batch-mybatis-jpa/files/write.txt"
      jpa-file-read-db-write-batch:
        use-yn: N
        cron-cycle: "0 36 16 * * *"
        chunk-size: 1000
        read-file-path: "C://workspace_platform/spring-batch-mybatis-jpa/files/read.txt"
      jpa-db-read-file-write-batch:
        use-yn: N
        cron-cycle: "0 27 11 * * *"
        chunk-size: 1000
        write-file-path: "C://workspace_platform/spring-batch-mybatis-jpa/files/write.txt"
